[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10.2.3"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# This redirect is key for Single Page Applications that handle routing internally
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

